/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rosjava_android_androidp1_FreeRTPSListener */

#ifndef _Included_com_github_rosjava_android_androidp1_FreeRTPSListener
#define _Included_com_github_rosjava_android_androidp1_FreeRTPSListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rosjava_android_androidp1_FreeRTPSListener
 * Method:    listener
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rosjava_android_androidp1_FreeRTPSListener_listener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
